### ISSUE TITLE
TS - Create Tour Schedule Object

### ISSUE THREAD

**Issue by rrice1** [nss-evening-cohort-8/bandz-adios-pantalones#3]
### User Story:
As a *Developer* I need a Tour Schedule javascript object to build my tour schedule list.
```js
{
    date: 1535691600000,
    city: 'Scratch Ankle',
    state: 'AL',
    venue: "Jim's Waterin' Hole",
    isSoldOut: 'false'
}
```
### Dev Notes:
*Create* a javascript object to represent the data for the tour schedule including a "sold out" Boolean
### Acceptance Criteria:
The main.js should contain a javascript object containing an array of values that represents the band tour schedule.

![tour](https://user-images.githubusercontent.com/34825229/45393405-602b5b00-b5f1-11e8-824c-e1ad959659df.JPG)

**Comment by MCrank** [comment]
Merged in PR #35
