### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by MCrank** [nss-evening-cohort-8/bandz-adios-pantalones#52]
Last thing we need to do is update the readme with the designated items.

## Description
This project is an exploration of javascript functions. I built an animal nuggetizer. I also printed some numbers to the DOM.

## Screenshots

- Put some screenshots here

## How to run this project

- Use npm to install http-server in your terminal:

```sh
npm install -g http-server
```

- Run the server

```sh
hs -p 8080
```

- Open your browser and navigate to:

```
localhost:8080
```

**Comment by rrice1** [comment]
#63 created for this too
