### ISSUE TITLE
TS - Background Image

### ISSUE THREAD

**Issue by rrice1** [nss-evening-cohort-8/bandz-adios-pantalones#7]
### User Story:
As a *User*, when I browse to the Tour Schedule page I should see a background image of the band
### Dev Notes:
*Create* the DIV to contain the background image named _**ts_background.png**_
*and* insert and style the img in accordance to the wireframe below
*Reference* Issue #15 

### Acceptance Criteria:
When a user browses to the tour schedule page the should see a picture of the band as the background image.

![tour](https://user-images.githubusercontent.com/34825229/45393405-602b5b00-b5f1-11e8-824c-e1ad959659df.JPG)

**Comment by MCrank** [comment]
Merged in as PR #30
