### ISSUE TITLE
TS - Populate List

### ISSUE THREAD

**Issue by rrice1** [nss-evening-cohort-8/bandz-adios-pantalones#8]
### User Story:
As a *User* I should see the band's tour schedule as a list when I browse to the tour schedule page.
*and* there should also be buttons to buy tickets and VIP packages for each tour.
### Dev Notes:
*Create* an HTML table that populates with the Band Tour Schedule
*and* create "Buy" and "VIP" buttons for each tour listed
*and* style the page according to the Moqup below.
### Acceptance Criteria:
*When* a user browses to the Tour Schedule page they should see a list of up coming tour shows
*and* they should be able to buy tickets for the show
*and* if they desire can buy a "VIP" package as well.

![tour](https://user-images.githubusercontent.com/34825229/45393405-602b5b00-b5f1-11e8-824c-e1ad959659df.JPG)

**Comment by MCrank** [comment]
Merged PR #48
